### ISSUE TITLE
1107 : Verification Failed

### ISSUE THREAD

**Issue by darrylmorley** [caprover/nginx-redirect#4]
I'm trying to add my domain to redirect but getting a 1107:Verfication failed error. The domain is pointing to the server and was previously succesfully tied to my app instance.

Any ideas on how to resolve this, please?

**Comment by githubsaturn** [comment]
Did you search the docs for 1107 error?

There are some workarounds mentioned in the docs.

**Comment by darrylmorley** [comment]
@githubsaturn 

I went with the below which has killed my whole server, nothing resolves and I'm currently moving websites to other hosts to get them back online. 

```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by githubsaturn** [comment]
https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui


Try this.

**Comment by githubsaturn** [comment]
For context: disabling the domain verification will not kill your server. Probably something else happened before that resulted in that.

**Comment by darrylmorley** [comment]
@githubsaturn I've got everything back up and running now. Thanks!
