### ISSUE TITLE
ARM Build

### ISSUE THREAD

**Issue by Alfagun74** [caprover/nginx-redirect#6]
Can we have an ARM build please?

**Comment by githubsaturn** [comment]
It's already there:

![image](https://github.com/caprover/nginx-redirect/assets/10582082/6be6fa32-3807-441a-9284-d0ca2c22737a)

**Comment by Alfagun74** [comment]
That is caprover/nginx-reverse-proxy not caprover/nginx-redirect

**Comment by githubsaturn** [comment]
Thank for the note! Added the multiarch for this image as well! Let me know if it doesn't work! 

![image](https://github.com/caprover/nginx-redirect/assets/10582082/86c495c1-fddd-445a-9e8e-b89dd69b1ec4)
